# Generated by Django 4.2.6 on 2023-10-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('product_id',
                 models.PositiveBigIntegerField()),
                ('description',
                 models.CharField(
                     max_length=200)),
            ],
        ),
    ]
